/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 7124115 (https://sketchfab.com/7124115)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/webcam-89d6eaf640c64d9aa6549e0b3fa54415
title: Webcam
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object010_PVC_Black_Matte_0: THREE.Mesh
    Sphere005_Glass_Clear_Distorted_0: THREE.Mesh
    ['Sphere005_Material_#37_0']: THREE.Mesh
    Sphere006_Glass_Clear_Distorted_0: THREE.Mesh
    ['Sphere006_Material_#37_0']: THREE.Mesh
    Sphere012_Glass_Clear_Distorted_0: THREE.Mesh
    ['Sphere012_Material_#37_0']: THREE.Mesh
    Object004_PVC_Black_Glossy_0: THREE.Mesh
    Object004_PVC_Black_Glossy_0_1: THREE.Mesh
    Sphere011_Glass_Clear_Distorted_0: THREE.Mesh
    ['Sphere011_Material_#37_0']: THREE.Mesh
    Sphere010_Glass_Clear_Distorted_0: THREE.Mesh
    ['Sphere010_Material_#37_0']: THREE.Mesh
    Object007_PVC_Black_Matte_0: THREE.Mesh
    Object008_webcamMS_scene_material_0: THREE.Mesh
    Sphere004_Glass_Clear_Distorted_0: THREE.Mesh
    ['Sphere004_Material_#37_0']: THREE.Mesh
    Object012_webcamMS_material3_0: THREE.Mesh
    Object006_PVC_Black_Matte_0: THREE.Mesh
    Object005_PVC_Black_Matte_0: THREE.Mesh
    Object003_PVC_Black_Matte_0: THREE.Mesh
    Object002_PVC_Black_Matte_0: THREE.Mesh
    Object001_PVC_Black_Glossy_0: THREE.Mesh
    ['12_0_921_0_PVC_Black_Glossy_0']: THREE.Mesh
    Object011_PVC_Black_Matte_0: THREE.Mesh
  }
  materials: {
    PVC_Black_Matte: THREE.MeshStandardMaterial
    Glass_Clear_Distorted: THREE.MeshStandardMaterial
    Material_37: THREE.MeshStandardMaterial
    PVC_Black_Glossy: THREE.MeshStandardMaterial
    webcamMS_scene_material: THREE.MeshStandardMaterial
    webcamMS_material3: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.13, 45.12, -11.24]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -19.38, -8.5]}>
              <mesh
                geometry={nodes.Object010_PVC_Black_Matte_0.geometry}
                material={nodes.Object010_PVC_Black_Matte_0.material}
              />
            </group>
          </group>
          <group position={[-0.06, 45.13, 19.61]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
            <group position={[-0.03, 1.16, 16.88]}>
              <mesh
                geometry={nodes.Sphere005_Glass_Clear_Distorted_0.geometry}
                material={nodes.Sphere005_Glass_Clear_Distorted_0.material}
              />
              <mesh
                geometry={nodes['Sphere005_Material_#37_0'].geometry}
                material={nodes['Sphere005_Material_#37_0'].material}
              />
            </group>
          </group>
          <group position={[-0.06, 45.13, 19.61]} rotation={[Math.PI / 2, -Math.PI / 3, -Math.PI]}>
            <group position={[-0.03, 1.16, 16.88]}>
              <mesh
                geometry={nodes.Sphere006_Glass_Clear_Distorted_0.geometry}
                material={nodes.Sphere006_Glass_Clear_Distorted_0.material}
              />
              <mesh
                geometry={nodes['Sphere006_Material_#37_0'].geometry}
                material={nodes['Sphere006_Material_#37_0'].material}
              />
            </group>
          </group>
          <group position={[-0.06, 45.13, 19.61]} rotation={[-Math.PI / 2, Math.PI / 3, 0]}>
            <group position={[-0.03, 1.16, 16.88]}>
              <mesh
                geometry={nodes.Sphere012_Glass_Clear_Distorted_0.geometry}
                material={nodes.Sphere012_Glass_Clear_Distorted_0.material}
              />
              <mesh
                geometry={nodes['Sphere012_Material_#37_0'].geometry}
                material={nodes['Sphere012_Material_#37_0'].material}
              />
            </group>
          </group>
          <group position={[-0.13, 45.12, 21.85]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 13.72, -8.5]}>
              <mesh
                geometry={nodes.Object004_PVC_Black_Glossy_0.geometry}
                material={nodes.Object004_PVC_Black_Glossy_0.material}
              />
              <mesh
                geometry={nodes.Object004_PVC_Black_Glossy_0_1.geometry}
                material={nodes.Object004_PVC_Black_Glossy_0_1.material}
              />
            </group>
          </group>
          <group position={[-0.06, 45.13, 19.61]} rotation={[-Math.PI / 2, Math.PI / 2, 0]}>
            <group position={[-0.03, 1.16, 16.88]}>
              <mesh
                geometry={nodes.Sphere011_Glass_Clear_Distorted_0.geometry}
                material={nodes.Sphere011_Glass_Clear_Distorted_0.material}
              />
              <mesh
                geometry={nodes['Sphere011_Material_#37_0'].geometry}
                material={nodes['Sphere011_Material_#37_0'].material}
              />
            </group>
          </group>
          <group position={[-0.06, 45.13, 19.61]} rotation={[Math.PI / 2, Math.PI / 3, -Math.PI]}>
            <group position={[-0.03, 1.16, 16.88]}>
              <mesh
                geometry={nodes.Sphere010_Glass_Clear_Distorted_0.geometry}
                material={nodes.Sphere010_Glass_Clear_Distorted_0.material}
              />
              <mesh
                geometry={nodes['Sphere010_Material_#37_0'].geometry}
                material={nodes['Sphere010_Material_#37_0'].material}
              />
            </group>
          </group>
          <group position={[-0.13, 10.25, 8.14]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 26.36]}>
              <mesh
                geometry={nodes.Object007_PVC_Black_Matte_0.geometry}
                material={nodes.Object007_PVC_Black_Matte_0.material}
              />
            </group>
          </group>
          <group position={[-0.13, 4.6, -13.86]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -22, 32.02]}>
              <mesh
                geometry={nodes.Object008_webcamMS_scene_material_0.geometry}
                material={materials.webcamMS_scene_material}
              />
            </group>
          </group>
          <group position={[-0.06, 45.13, 19.61]} rotation={[-Math.PI / 2, -Math.PI / 3, 0]}>
            <group position={[-0.03, 1.16, 16.88]}>
              <mesh
                geometry={nodes.Sphere004_Glass_Clear_Distorted_0.geometry}
                material={nodes.Sphere004_Glass_Clear_Distorted_0.material}
              />
              <mesh
                geometry={nodes['Sphere004_Material_#37_0'].geometry}
                material={nodes['Sphere004_Material_#37_0'].material}
              />
            </group>
          </group>
          <group position={[-0.13, 45.12, 14.13]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 5.99, -8.5]}>
              <mesh geometry={nodes.Object012_webcamMS_material3_0.geometry} material={materials.webcamMS_material3} />
            </group>
          </group>
          <group position={[-0.13, 5.61, 7.81]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -0.32, 31.01]}>
              <mesh
                geometry={nodes.Object006_PVC_Black_Matte_0.geometry}
                material={nodes.Object006_PVC_Black_Matte_0.material}
              />
            </group>
          </group>
          <group position={[-0.13, 7.54, 8.14]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 29.08]}>
              <mesh
                geometry={nodes.Object005_PVC_Black_Matte_0.geometry}
                material={nodes.Object005_PVC_Black_Matte_0.material}
              />
            </group>
          </group>
          <group position={[-0.13, 45.18, 6.83]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -1.31, -8.56]}>
              <mesh
                geometry={nodes.Object003_PVC_Black_Matte_0.geometry}
                material={nodes.Object003_PVC_Black_Matte_0.material}
              />
            </group>
          </group>
          <group position={[-0.13, 30.76, 8.14]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 5.86]}>
              <mesh
                geometry={nodes.Object002_PVC_Black_Matte_0.geometry}
                material={nodes.Object002_PVC_Black_Matte_0.material}
              />
            </group>
          </group>
          <group position={[-0.13, 69.37, 8.14]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, -32.75]}>
              <mesh
                geometry={nodes.Object001_PVC_Black_Glossy_0.geometry}
                material={nodes.Object001_PVC_Black_Glossy_0.material}
              />
            </group>
          </group>
          <group position={[-4.57, 45.13, 13.15]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[4.44, 5.02, -8.52]}>
              <mesh
                geometry={nodes['12_0_921_0_PVC_Black_Glossy_0'].geometry}
                material={nodes['12_0_921_0_PVC_Black_Glossy_0'].material}
              />
            </group>
          </group>
          <group position={[-0.13, 45.12, 8.14]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, -8.5]}>
              <mesh
                geometry={nodes.Object011_PVC_Black_Matte_0.geometry}
                material={nodes.Object011_PVC_Black_Matte_0.material}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
